### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [dstructs/matrix-reviver#1]
Final edit waiting on dstructs/matrix#10 (and possibly compute-io/cast-arrays#2).

**Comment by Planeshifter** [comment]
Looks good to me. One question: While having to type `JSON.parse( mstr, revive );` is explicit, it might be a bit inconvenient. Thought about providing a helper function which wraps `JSON.parse` with the second parameter pre-applied?

**Comment by kgryte** [comment]
Probably a second module. Making this that module would preclude combining multiple revivers during parsing. For instance, atm, this `reviver` function could be used within a single "master" reviver:

``` javascript
var matrixReviver = require( 'dstructs-matrix-reviver' );

function revive( key, value ) {
    var v;
    v = matrixReviver( key, value );
    if ( v !== value ) {
        return v;
    }
    v = nextReviver( key, value );
    ...
    return value;
}
```

**Comment by Planeshifter** [comment]
Good point. Eventually, we could have a single `fromJSON`-like function which takes a string and correctly revives it for any of our `dstructs`. Would be handy for command-line usage.

**Comment by kgryte** [comment]
Yep. Agreed.

**Comment by kgryte** [comment]
Closing as pending issues have been resolved.
